application: projet-ecole
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js

- url: /lib
  static_dir: lib

- url: /html
  script: html

- url: /fonts
  static_dir: fonts

- url: /css
  static_dir: css

- url: /admin/.*
  script: main.app
  login: required
  auth_fail_action: unauthorized

- url: /taskqueues/.*
  script: main.app
  login: admin
  auth_fail_action: unauthorized

- url: /Admin/.*
  script: main.app
  login: required
  auth_fail_action: unauthorized

- url: /auth/logout
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
